import pieIcon from './pie.png';
import pieFocusedIcon from './pie-focused.png';
import coinIcon from './coin.png';
import coinFocusedIcon from './coin-focused.png';
import magnifierIcon from './magnifier.png';
import magnifierFocusedIcon from './magnifier-focused.png';
import bellIcon from './bell.png';
import bellFocusedIcon from './bell-focused.png';
import personIcon from './person.png';
import personFocusedIcon from './person-focused.png';

export const PieIcon:string = pieIcon;
export const PieFocusedIcon:string = pieFocusedIcon;
export const CoinIcon:string = coinIcon;
export const CoinFocusedIcon:string = coinFocusedIcon;
export const MagnifierIcon:string = magnifierIcon;
export const MagnifierFocusedIcon:string = magnifierFocusedIcon;
export const BellIcon:string = bellIcon;
export const BellFocusedIcon:string = bellFocusedIcon;
export const PersonIcon:string = personIcon;
export const PersonFocusedIcon:string = personFocusedIcon;
