import pieIcon from './pie.png';
import pieFocusedIcon from './pie-focused.png';
import pieDisabledIcon from './pie-disabled.png';
import chartIcon from './chart.png';
import chartFocusedIcon from './chart-focused.png';
import coinIcon from './coin.png';
import coinFocusedIcon from './coin-focused.png';
import magnifierIcon from './magnifier.png';
import magnifierFocusedIcon from './magnifier-focused.png';
import bellIcon from './bell.png';
import bellFocusedIcon from './bell-focused.png';
import personIcon from './person.png';
import personFocusedIcon from './person-focused.png';
import personWhiteIcon from './person-white.png';
import capIcon from './cap.png';
import arrowUpwardIcon from './arrow-upward.png';
import arrowDownwardIcon from './arrow-downward.png';
import amazonIcon from './amazon.png';
import appleIcon from './apple.png';
import googleIcon from './google.png';
import shopifyIcon from './shopify.png';
import teslaIcon from './tesla.png';
import verticalFilterIcon from './vertical-filter.png';
import verticalFilterFocusedIcon from './vertical-filter-focused.png';
import horizontalFilterIcon from './horizontal-filter.png';
import horizontalFilterFocusedIcon from './horizontal-filter-focused.png';

export const PieIcon:string = pieIcon;
export const PieFocusedIcon:string = pieFocusedIcon;
export const PieDisabledIcon:string = pieDisabledIcon;
export const ChartIcon:string = chartIcon;
export const ChartFocusedIcon:string = chartFocusedIcon;
export const CoinIcon:string = coinIcon;
export const CoinFocusedIcon:string = coinFocusedIcon;
export const MagnifierIcon:string = magnifierIcon;
export const MagnifierFocusedIcon:string = magnifierFocusedIcon;
export const BellIcon:string = bellIcon;
export const BellFocusedIcon:string = bellFocusedIcon;
export const PersonIcon:string = personIcon;
export const PersonFocusedIcon:string = personFocusedIcon;
export const PersonWhiteIcon:string = personWhiteIcon;
export const CapIcon:string = capIcon;
export const ArrowUpwardIcon:string = arrowUpwardIcon;
export const ArrowDownwardIcon:string = arrowDownwardIcon;
export const AmazonIcon:string = amazonIcon;
export const AppleIcon:string = appleIcon;
export const GoogleIcon:string = googleIcon;
export const ShopifyIcon:string = shopifyIcon;
export const TeslaIcon:string = teslaIcon;
export const VerticalFilterIcon:string = verticalFilterIcon;
export const VerticalFilterFocusedIcon:string = verticalFilterFocusedIcon;
export const HorizontalFilterIcon:string = horizontalFilterIcon;
export const HorizontalFilterFocusedIcon:string = horizontalFilterFocusedIcon;
